#!/bin/bash
phantomjs runner.js | ffmpeg -y -c:v png -f image2pipe -r 25 -t 10  -i - -c:v libx264 -pix_fmt yuv420p -movflags +faststart ../webpage.mp4
# phantomjs runner.js

# # ffmpeg -start_number 10 -i webage.png -c:v libx264 -r 25 -pix_fmt yuv420p -movflags +faststart ../webpage.mp4